url: "https://eligibilityrules.org"
baseurl: ""

title: "EligibilityRules.org"
description: "Open source government eligibility rules"

plugins:
  - jekyll-sitemap

collections:
  services:
    output: true
    permalink: /services/:path/
  jurisdictions:
    output: true
    permalink: /jurisdictions/:path/
  rulesets:
    output: true
    permalink: /rulesets/:name.json

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "jurisdictions"
    values:
      layout: "jurisdiction"
  - scope:
      path: ""
      type: "rulesets"
    values:
      layout: "ruleset-json"

# Load YAML data files
data_dir: data

exclude:
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
  - node_modules
  - Gemfile
  - Gemfile.lock
